# -*- coding: utf-8 -*-
"""tinc_2h.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NK4qmdnG3xHiZEoZRNbNNN5i3XHyKi2l
"""

''' b
str = input()
used_nums = set()
twice_nums = set()
ans = []
for char in str:
    if char.isdigit():
        if char in used_nums:
            twice_nums.add(char)
        used_nums.add(char)

if (len(twice_nums) != 0):
    for value in twice_nums:
        ans.append(value)
    ans.sort()
    print(' '.join(ans))
else:
    print("NO")
    '''

''' f
n = int(input())
languages = {}
for i in range(n):
    langs_amount = int(input())
    for j in range(langs_amount):
        temp_lang = input()
        if temp_lang not in languages:
            languages[temp_lang] = []

        languages[temp_lang].append(i)

everyone = []
for key in languages:
    if len(languages[key]) == n:
        everyone.append(key)
print(len(everyone))

for lang in everyone:
    print(lang)

print(len(languages))
for key in languages:
    print(key)
'''

with open('input.txt', 'r') as fin:
    dic = {}
    max = 0;

    for line in fin:
        words = line.split()
        for word in words:
            if word not in dic:
                dic[word] = 0
            dic[word] += 1
            if dic[word] > max:
                max = dic[word]

    max_words = []
    for word in dic:
        if dic[word] == max:
            max_words.append(word)

    max_words.sort()
    print(max_words[0])

